#!/bin/bash
echo "🔥 Serving entire workspace from project root..."
echo ""
echo "Structure:"
echo "- my-super-app/"
echo "  - ssr-hub/dist/ ← TEST-VIEWER.html here"
echo "  - ssr-react/dist/ ← React modules"
echo "  - ssr-vue2/dist/ ← Vue2 modules"
echo "  - ssr-vue3/dist/ ← Vue3 modules"
echo ""
echo "This makes relative paths work correctly!"
echo ""
echo "Browse to: http://localhost:3000/my-super-app/ssr-hub/dist/TEST-VIEWER.html"
echo ""
npx serve -p 3000
